### ISSUE TITLE
Output Directory

### ISSUE THREAD

**Issue by 1MaJKeL1** [tzurp/performance-total#12]
Hi,

Could you add the possibility to specify outputDir

Best regards

DM

**Comment by tzurp** [comment]
@1MaJKeL1, do you mean to specify absolute path or relative?

**Comment by 1MaJKeL1** [comment]
relative 
such example

services: [
    ['chromedriver'],
    ['performancetotal',
      {
        outputDir: './Results/performance',
        disableAppendToExistingFile: false,
        performanceResultsFileName: "performance-results",
        dropResultsFromFailedTest: false
      }]
    ]

**Comment by tzurp** [comment]
> relative
> such example
> 
> services: [
> ['chromedriver'],
> ['performancetotal',
> {
> outputDir: './Results/performance',
> disableAppendToExistingFile: false,
> performanceResultsFileName: "performance-results",
> dropResultsFromFailedTest: false
> }]
> ]

@1MaJKeL1, please check version 1.0.9-1 (beta) here: [https://www.npmjs.com/package/wdio-performancetotal-service/v/1.0.9-1](https://www.npmjs.com/package/wdio-performancetotal-service/v/1.0.9-1).
I added a config property: performanceResultsDirectory (see Readmy.md for details)

**Comment by tzurp** [comment]
The feature was added to the Beta version, with no response from the user. Closing the issue.

**Comment by 1MaJKeL1** [comment]
Hi,
I had version 1.0.9 and beta 9-1 it works fine after adding attributes

        performanceResultsDirectory: 'Results/performance',

thanks a lot 

Br

MaJKeL
