### ISSUE TITLE
Console-Log: Performance-Total: flushing to file: ...

### ISSUE THREAD

**Issue by muhserks** [tzurp/performance-total#24]
Hi,

https://github.com/tzurp/performance-total/blob/139cb2cbf4c12d66eee15640aeda4c593e7b18dd/src/performance-logger.ts#L26
Would it be possible to remove this console log? 
If not, would it be possible to put it into some kind of debug flag/mode so that this output can be disabled? 

Don't know what the purpose should be but for me it is just blowing up the logs without any real benefit.

Thanks & Regards

**Comment by tzurp** [comment]
@muhserks thanks for your PR but I need to add a service option to turn off the logs.

**Comment by tzurp** [comment]
@muhserks fixed in 2.1.1
