### ISSUE TITLE
Appending to results.json creates invalid JSON

### ISSUE THREAD

**Issue by markcorgan** [tzurp/performance-total#26]
Hi. When `disableAppendToExistingFile=false`, the performance data appended to the `.json` file is incorrect. It appends an array to the existing array in the file rather than appending an object to the existing array in the file. I believe this line is the culprit where it appends the array directly:

https://github.com/tzurp/performance-total/blob/99720532ea2d788a8d3c9f00acd11a2731208ed6/src/performance-analyzer.ts#L58

Example:

What it's doing (which is invalid JSON):

`[
  {
    "name": "Create and remove a set",
    "brName": "Chrome",
    "avgTime": 5405,
    "sem": 0,
    "repeats": 1,
    "minValue": 5405,
    "maxValue": 5405,
    "earliestTime": "12/8/2021, 2:13:55 PM",
    "latestTime": "12/8/2021, 2:13:55 PM"
  }]
  [{
    "name": "Create and remove a set",
    "brName": "Chrome",
    "avgTime": 5383,
    "sem": 22,
    "repeats": 2,
    "minValue": 5361,
    "maxValue": 5405,
    "earliestTime": "12/8/2021, 2:13:55 PM",
    "latestTime": "12/8/2021, 2:15:17 PM"
  }
]`

What it should be doing:

`[
  {
    "name": "Create and remove a set",
    "brName": "Chrome",
    "avgTime": 5405,
    "sem": 0,
    "repeats": 1,
    "minValue": 5405,
    "maxValue": 5405,
    "earliestTime": "12/8/2021, 2:13:55 PM",
    "latestTime": "12/8/2021, 2:13:55 PM"
  },
  {
    "name": "Create and remove a set",
    "brName": "Chrome",
    "avgTime": 5383,
    "sem": 22,
    "repeats": 2,
    "minValue": 5361,
    "maxValue": 5405,
    "earliestTime": "12/8/2021, 2:13:55 PM",
    "latestTime": "12/8/2021, 2:15:17 PM"
  }
]`

**Comment by tzurp** [comment]
@markcorgan fixed in v2.1.1

**Comment by markcorgan** [comment]
> @markcorgan fixed in v2.1.1

Awesome. Thank you!
