### ISSUE TITLE
[Feature Request] Add Chart generation

### ISSUE THREAD

**Issue by conradkirschner** [tzurp/performance-total#28]
I had to build a small script to generate the chart. A build in Feature would be cool, from my perspective.

what do you think?

**Comment by tzurp** [comment]
@conradkirschner actually that was the original plan until I realized how easy is to open the exported *.csv file with spreadsheet app (MS Excel) and generate the chart. If you still want to add it I would love to get a code or PR.

**Comment by tzurp** [comment]
Closing this issue due to no response for a long time.
